title: "Grammaire russe"
description: "Un site pour apprendre la grammaire russe avec des exemples et des exercices."
theme: just-the-docs
url: "https://toshkine.github.io/ruslessons"
lang: "fr"
search_enabled: true
show_breadcrumbs: true

# Footer
back_to_top: true
back_to_top_text: "Retour en haut"
footer_content: "© 2024 Grammaire russe. Tous droits réservés."

# Configurations supplémentaires
last_edit_timestamp: true # Montre la dernière modification
last_edit_time_format: "%d %b %Y" # Format de la date pour la dernière modification
