title: "Grammaire russe"
description: "Un site pour apprendre la grammaire russe avec des exemples et des exercices."
theme: just-the-docs
url: "https://toshkine.github.io/ruslessons"
baseurl: "/ruslessons"
lang: "fr"

search_enabled: true
show_breadcrumbs: true

# Footer
back_to_top: true
back_to_top_text: "Retour en haut"

# Configuration pour détecter la dernière modification à partir du dernier commit
plugins:
  - jekyll-seo-tag
  - jekyll-github-metadata
  - jekyll-last-modified-at

# Configurations supplémentaires
last_edit_timestamp: true
last_edit_time_format: "%d %b %Y"

# Retirer le lien GitHub du footer
gh_edit_link: false

